""".

Revision ID: 00ae681828cc
Revises: f620460264b0
Create Date: 2017-02-21 22:55:59.204290

"""

# revision identifiers, used by Alembic.
revision = '00ae681828cc'
down_revision = 'f620460264b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'authod_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('authod_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['authod_id'], ['id'])
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
