""".

Revision ID: 7363c1eb1f85
Revises: cc4af199e79b
Create Date: 2017-02-20 20:30:18.131267

"""

# revision identifiers, used by Alembic.
revision = '7363c1eb1f85'
down_revision = 'cc4af199e79b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
