"""selenium

Revision ID: bd831af3e1b5
Revises: 249426fc8a24
Create Date: 2017-02-25 21:53:23.636453

"""

# revision identifiers, used by Alembic.
revision = 'bd831af3e1b5'
down_revision = '249426fc8a24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
