""".

Revision ID: e493e07ca715
Revises: 07ed23f1c076
Create Date: 2017-02-20 23:08:24.179336

"""

# revision identifiers, used by Alembic.
revision = 'e493e07ca715'
down_revision = '07ed23f1c076'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
